### PR TITLE
system tests workflow

### PR DESCRIPTION
**Pull request by alstanchev**
A system tests workflow. 
Resolves: #2029

### CODE REVIEW

**Comment by alstanchev** [comment]
@thjaeckle it is posible that it may need fine tuning as i only ran it localy and havent tested the result s and logs publishing.

**Comment by thjaeckle** [comment]
@alstanchev did you see?
I tried running the system-tests GitHub action - and it failed .. but the output seemed strange to me, because in "Setup JDK" step it already needed the Ditto pom.xml?!

**Comment by alstanchev** [comment]
Yes it is strange to me too, but comparing it to the maven workflow where the checkout is first I suspect there is something underneath that expects the code to be present (maybe because of the maven caching) I made a change but saw some other things that maybe will be different compared to local run with act. So I went the documentation rabbit hole. Will commit the change later

**Comment by thjaeckle** [comment]
Please go ahead an directly commit to `master` branch if that helps/speeds you up ..

**Pull request merged**
