### PR TITLE
#1893 fix ensuring the consistency when doing signal enrichment

### PR DESCRIPTION
**Pull request by thjaeckle**
Resolves: #1893

### CODE REVIEW

**Comment by kyberpunk** [comment]
Hi @thjaeckle you are very fast, looks perfect. Just one question: how exactly we can enforce the new behavior? Should we somehow setup ditto headers? Thank you.

**Comment by thjaeckle** [comment]
@kyberpunk I would make this the default behavior - we want to ensure consistency here
There is also an optimisation in place, which does not apply the rather cost-expensive "history lookup" - when there is no newer modification of the thing, the "history lookup" is skipped and the in-memory representation is used for retrieving "extraFields".

That should for 95% of cases optimise and only for high-frequency cases add some additional cost.

**Comment by thjaeckle** [comment]
@alstanchev @kalinkostashki could you please have a look?
Would want to release a 3.5.3 soon

Could you please run system-tests for this PR as part of a review? That would be super

**Comment by kalinkostashki** [comment]
> @alstanchev @kalinkostashki could you please have a look? Would want to release a 3.5.3 soon
> 
> Could you please run system-tests for this PR as part of a review? That would be super

hey @thjaeckle,
sure will do :)

**Review by kalinkostashki — APPROVED** [review]
LGTM :+1:

**Pull request merged**
