### PR TITLE
#1591 add SSO via OIDC to Ditto UI

### PR DESCRIPTION
**Pull request by thjaeckle**
* make it configurable which OIDC issuers to use
* re-did a lot of the existing configuration of the Ditto UI
* added typing for Environment

Resolves: #1591

### CODE REVIEW

**Comment by thfries** [comment]
Highly appreciated! Thank you for introducing that lot of typing improvements.

**Comment by thjaeckle** [comment]
@thfries sure, my pleasure :)

Could you have a look on the PR as a reviewer?

**Comment by thfries** [comment]
Sure, I already looked at the code changes, but I can check it out and take a look.
I fear that I will not be able to set up the OICD infrastructure. We don't have any authorization server in place. Would this work with Google authentication (but I still need a ditto instance that can be reached in the internet, I assume)? I will do my best...

**Comment by thjaeckle** [comment]
@thfries I added a subfolder in the `ui` folder containing a `docker-compose.yml` in order to start a mock SSO (OAuth2) server.  
I also developed the SSO feature testing this .. 

With the updated `environmentTemplates.json` there is already an environment named `oidc_example` - choosing that should connect to the started OAuth2 mock server.

**Comment by thjaeckle** [comment]
I did now my last commit for this PR .. reflecting the searchFilter's current search also via a query param `filter` - so that this "survives" the SSO redirect as well.

**Pull request merged**
