### PR TITLE
Execute cronjob with non-root user

### PR DESCRIPTION
**Pull request by gbudinov**

### CODE REVIEW

**Review by alstanchev — APPROVED** [review]
@thjaeckle in some systems the security advisor warns on running containers with root user. 
This PR fixes that.

**Comment by thjaeckle** [comment]
Shouldn't the user and group be configurable? AFAIR we also made the image configurable to run for the cron job, so a different user might be wanted.

**Comment by alstanchev** [comment]
Good point. I will make it configurable.

**Comment by alstanchev** [comment]
Closing this PR and will provide the changes in another one.

**Pull request closed without merging**
