### PR TITLE
UI - Build UI with esbuild

### PR DESCRIPTION
**Pull request by thfries**
Hello,

please find this PR that introduces bundling of the UI.

I started with [webpack](https://webpack.js.org) but ended up with [esbuild](https://esbuild.github.io). esbuild seems to do exactly what is needed and ended up with a very lean setup.

Some boiler plate code could be removed and some files were structured differently.

The PR is still in draft and needs some more testing (and maybe some more improvements).

Any feedback welcome.

@thjaeckle: Can we introduce the build step as a github action? The `index.html` in the ui root folder is still the entry point but everything else will be used from the new `dist` folder. There is a brief readme that describe the build steps and the details can be found in the `package.json`.

Thomas

### CODE REVIEW

**Comment by thjaeckle** [comment]
@thfries you forgot to commit the `package.json` and have it still listed in `.gitignore`
That would probably need to change ;) 

I just wanted to have a look at it an try it out - which of course failed ;)

**Comment by thfries** [comment]
Hi @thjaeckle,
yes package.json would be helpful 😀. Sorry.
I did some more work.
Seems like some libraries are intended to be integrated via cdn and it would need some hick-ups to integrate them in the build process (like ace and bootstrap-icons). So I kept them as is (but ace is then not checked by `nom update` ☹️)

**Comment by thfries** [comment]
Hi @thjaeckle,

found some fixes during testing and looks good now (automated test are needed...). So removing draft state.
I prepared the adaption to the docker file, but I m not familiar with using that.

Please let me know if you have remarks. I will try out on another workspace, too (to avoid further missing commits) 😀

**Comment by thfries** [comment]
> Hi @thfries
> 
> Looks good to me, thanks a lot for this :) I adjusted the GH Actions jobs. I hope that all will work :D

Hi @thjaeckle , works great. Thanks a lot for your support!

**Pull request merged**
