### PR TITLE
[#1592] provide "Bearer" authentication for devops resources controlled via UI

### PR DESCRIPTION
**Pull request by thjaeckle**
* added radiobutton groups so that "Authorize" modal clearly shows/states which authentication to use where
* reduced to a single "Authorize" button in modal
* simplified environment a bit

Resolves: #1592

Screenshot of modal:
Screen Shot 2023-03-06 at 20 12 36 PM

### CODE REVIEW

**Comment by thjaeckle** [comment]
@thfries could you please take a look and check if this is also in your opinion good? :)

Right after creating the PR I thought that the "Authorize" modal should mabye group by main / devops credentials and not by the authentication type.
So:
1. Main user
a) basic auth
b) bearer auth
c) pre-authenticated auth
2. Devops user
a) basic auth
b) bearer auth

What do you think?

**Comment by thjaeckle** [comment]
I would plan the Ditto release 3.2.0 for tomorrow.
An approval of this PR would be nice to make it into the release.
/cc @thfries @alstanchev @jufickel-b

**Comment by thfries** [comment]
The second approach is better. In the first case, the radio buttons do not fit, because you can work with both users in parallel (it is not either / or, you can enter both).

The separation of DevOps API and "Main" API is a bit confusing. There are two variants to retrieve the connections. The DevOps user is currently only needed for the "old" Ditto 2 way to retrieve connections.
So I think the separate authorize method for the DevOps user makes more sense for the new feature in #1590

Do you think we should remove the Ditto 2 support for connections?

**Comment by thjaeckle** [comment]
> The separation of DevOps API and \"Main\" API is a bit confusing. There are two variants to retrieve the connections. The DevOps user is currently only needed for the \"old\" Ditto 2 way to retrieve connections.

Hm, actually no. There are 2 variants to retrieve connections, yes.
However both require the "DevOps authentication" (either via basic auth or OAuth, depending on how Ditto is configured).
The "main user" can never access connections in Ditto.

I think the proposed PR does correctly reflect the current possibilities.

Also no need to drop Ditto 2 support.

**Comment by thfries** [comment]
Hi @thjaeckle,
I tested and reviewed and it looks good to me.
(in case of Things service, you need to enter the same bearer twice now? but it works)

Thanks!

**Comment by thjaeckle** [comment]
Thanks @thfries .

Ah, yes. For Bosch IoT things the end user can have access to the connections.
The Bearer tokens could still differ of course.
The solution Admin does not have automatically access to things for example.

**Pull request merged**
