### PR TITLE
#1883 return pre-authenticated configuration to location-snippet

### LINKED ISSUE #1833: Regression: When using BASIC auth the pre-authenticated header is not forwarded to gateway pod
The changes introduced in #1787 are seemingly incompatible with the built-in ingress controller, which is the [Ingress-Nginx Controller](https://kubernetes.github.io/ingress-nginx/) maintained by Kubernetes community. While somewhat compatible with the "official" [NGINX Ingress Controller](https://docs.nginx.com/nginx-ingress-controller/) maintained by the NGINX the company, there are some incompatibilities. The change from #1787 is one of them. Juding by the https://github.com/kubernetes/ingress-nginx repo, the `proxy-set-header` is always part of the location and is not used anywhere else, therefore it seems that it must be part of the `location-snippet`.

The clean way to configure `proxy-set-headers` in the *Ingress-Nginx Controller* is to create a [ConfigMap](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-set-headers) with the headers and to reference them in the central `nginx-configuration` ConfigMap.

I decided actually to simply return the strings where they were, but also to keep them in the location where #1787 introduce them, in order to keep Ditto working with the Ingress controller that @mladBlum is using.

### PR DESCRIPTION
**Pull request by RockyMM**
Necessary for the Ingress-Nginx Controller. Fixes #1833

### CODE REVIEW

**Comment by RockyMM** [comment]
@mladBlum take a look, I think this change should not affect you.

**Comment by RockyMM** [comment]
> Hm, should I increase the chart version?

The next semver should be `3.4.2-1`. I kept the `appVersion` at `3.4.2`. Maybe there is a way to only release the Helm chart?

**Comment by thjaeckle** [comment]
> @RockyMM do you know if we can use version 3.4.2.1 in Helm? The forth digit would be nice in this case ..

Probably not .. so `3.4.3-0` would be fine for me (if that passes linting) - as a "pre-release of 3.4.3".
Otherwise, just bump it to `3.4.3` - then Chart and appVersion are no longer in sync until the next minor release `3.5.0`.

**Comment by thjaeckle** [comment]
@kalinkostashki could you review? I know you also were looking into solutions..

**Review by kalinkostashki — APPROVED** [review]
LGTM :+1:

**Review by thjaeckle — APPROVED** [review]

**Pull request merged**
