### PR TITLE
#1614 enabled creating a thing for a "MergeThing" when it does not yet exist

### PR DESCRIPTION
**Pull request by thjaeckle**
* enhanced ModifyToCreateThingTransformer to also handle "MergeThing" in addition to "ModifyThing"
* adjusted ThingsRoute to also support using "_policy" and "_copyPolicyFrom"

Resolves: #1614

### CODE REVIEW

**Comment by thjaeckle** [comment]
Added missing documentation.
@alstanchev FMPOV the issue would be ready to be reviewed. If you find the time, that would be awesome :)

**Comment by thjaeckle** [comment]
@alstanchev / @kalinkostashki / @jufickel-b it would be great if someone could review this PR.

If no objections are filed, PR will be merged also without review.

**Review by ProfessorSleepy — APPROVED** [review]
LGTM :)

**Review by kalinkostashki — APPROVED** [review]
LGTM :)

**Pull request merged**
