### PR TITLE
delete duplicate nginx body style

### PR DESCRIPTION
**Pull request by neottil**
delete duplicate nginx body style in all deployments nginx configurations

### CODE REVIEW

**Comment by neottil** [comment]
@thjaeckle how can I fix the lint-chart check? I see in the code that the 2"hart version is effectively set by release-job".

**Comment by thjaeckle** [comment]
@neottil thanks for the PR - you just need to bump the `version` to next patch version - the linting enforces that the version is updated (and checks against `master` branch).

**Comment by neottil** [comment]
@thjaeckle now it's ok.
Thanks

**Review by thjaeckle — APPROVED** [review]
LGTM, thanks for the PR 👍

**Pull request merged**
