### PR TITLE
fix that non-successful message responses were not displayed in ACE editor

### PR DESCRIPTION
**Pull request by thjaeckle**
* only successful responses were displayed
* however, messages might e.g. be answered with a 400 (bad request) and useful information as response

### CODE REVIEW

**Comment by thjaeckle** [comment]
@thfries I noticed that only successful message responses were displayed in the "response" ace editor
We use e.g. 400 "bad request" for validation errors and it would be really helpful to display such responses.

Could you please have a short look on the improvement/fix?

I also thought that displaying the status code might also be helpful, but had no good idea to add it to the current layout.

**Comment by thfries** [comment]
Hi @thjaeckle, I am missing the usual error toast now that is popping up in case of errors but I did not find a way to show it in addition to filling the response editor.
The toast with the error message did not work for you? By clicking on it you can prevent it from disappearing while you keep the mouse on it.
Can you please take a look at the toast behaviour? May be this can be / needs to be improved. That should work all errors from ditto in a similar way. Thanks for you feedback.

**Comment by thjaeckle** [comment]
Thanks, will look into the toasts for other errors ..

**Comment by thjaeckle** [comment]
@thfries I now additionally show the "error toast" and improved that, displaying also errors which are not in "Ditto error format".

**Comment by thfries** [comment]
Nice! I like it. Thank you!

**Pull request merged**
